# 任务配置
task:
  # 要执行的任务编号: 1, 1p, 2, 3, 4, 4p
  id: "2"
  # 选择要使用的账号序号（从1开始）
  accounts: [1, 2]
  # 搜索关键词列表
  keywords:
    - "机械键盘"
    - "无线键盘"
    - "游戏键盘"
  # 任务1和2的配置
  search:
    pages_per_keyword: 3  # 每个关键词抓取页数
    dynamic_times: 5      # 动态监控次数
    interval_minutes: 30  # 监控间隔（分钟）
  # 任务4的配置
  homepage:
    scroll_times: 10  # 向下滚动次数